---
# https://github.com/nvm-sh/nvm#important-notes
- name: Install
  tags: [install]
  homebrew: name=nvm update_homebrew=yes
- name: Setup config
  tags: [config]
  blockinfile:
    path: ~/.config/zsh/local.zsh
    state: present
    marker: "# {mark} nvm ANSIBLE MANAGED BLOCK"
    block: |
      export NVM_DIR="${XDG_DATA_DIR:-$HOME/.local/share}/nvm"
      [ -s "/usr/local/opt/nvm/nvm.sh" ] && . "/usr/local/opt/nvm/nvm.sh"  # This loads nvm
