---
# https://github.com/nvm-sh/nvm#important-notes
- name: Install
  tags: [install]
  homebrew: name=nvm update_homebrew=yes
- name: Setup config
  tags: [config]
  blockinfile:
    path: ~/.config/zsh/local.zsh
    state: present
    marker: "# {mark} nvm ANSIBLE MANAGED BLOCK"
    block: |
      export NVM_DIR="$XDG_DATA_HOME/nvm"
      export NVM_EXE="$HOMEBREW_PREFIX/opt/nvm/nvm.sh"
      # nvm loaded in direnv
