repos:
-   repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.7.1.1
    hooks:
    -   id: shellcheck
        files: ^minimal/.*$
-   repo: https://github.com/ansible/ansible-lint.git
    rev: v4.2.0
    hooks:
      -   id: ansible-lint
          files: ^ansible/.*\.(yaml|yml)$
