---
- name: Create data folder
  file:
    path: ~/.local/share
    state: directory
- name: Create default venv
  shell:
    cmd: python3 -m venv ~/.local/share/venv
    creates: ~/.local/share/venv
- name: Install
  shell:
    cmd: ~/.local/share/venv/bin/pip install pipx
    creates: ~/.local/share/venv/bin/pipx
- name: Add venv PATH and PIPX path
  tags: [config]
  blockinfile:
    path: ~/.config/zsh/local.zsh
    state: present
    marker: "# {mark} pipx ANSIBLE MANAGED BLOCK"
    insertbefore: BOF
    block: |
      export LOCAL_VENV="${XDG_DATA_DIR:-$HOME/.local/share}/venv"
      export PIPX_HOME="${XDG_DATA_DIR:-$HOME/.local/share}/pipx"
      export PIPX_BIN_DIR="$PIPX_HOME/bin"
      export PATH="$LOCAL_VENV/bin:$PATH:$PIPX_BIN_DIR"
- name: Install
  shell: pipx install {{ item }}
  loop:
    - ansible
    - pre-commit
    - virtualenv
