export PS1="\w > "
PS1='${debian_chroot:+($debian_chroot)}\[\033[01;34m\]\w\[\033[00m\]\n> '


# https://github.com/tmux/tmux/issues/120#issuecomment-143375064
# setting explicitly for cli programs behave properly
export TERM=xterm-256color

# set default editor to nvim
nvim=$(which nvim)
export EDITOR=$nvim
export VIEWER="$nvim -R"

alias vim='nvim'

source "$HOME/.config/bash/local.sh"
