#!/bin/bash
# ^ setting shebang for identify recognition

export PS1='${debian_chroot:+($debian_chroot)}\[\033[01;34m\]\w\[\033[00m\]\n > '

# set default editor to nvim
nvim=$(which nvim)
export EDITOR=$nvim
export VIEWER="$nvim -R"

alias vim='nvim'

export PIPENV_VENV_IN_PROJECT=1

# clean home dir
export INPUTRC="$HOME/.config/bash/inputrc"
export PYTHONSTARTUP="$HOME/.config/python/pythonrc"
export LESSHISTFILE="$HOME/.cache/less/lesshst"

source "$HOME/.config/bash/local.sh"
