---
# tasks file for roles/skel
- name: Add tap
  tags: [install]
  homebrew_tap:
    name:
      - universal-ctags/universal-ctags
- name: Install
  tags: [install]
  homebrew:
    name: universal-ctags
    install_options: [HEAD]
    update_homebrew: yes
- name: Setup config
  tags: [setup]
  blockinfile:
    path: ~/.config/zsh/local.zsh
    state: present
    marker: "# {mark} ctags ANSIBLE MANAGED BLOCK"
    block: |
      # Sqlite
      # For compilers to find sqlite you may need to set:
      export LDFLAGS="-L/usr/local/opt/sqlite/lib $LDFLAGS"
      export CPPFLAGS="-I/usr/local/opt/sqlite/include $CPPFLAGS"
      # For pkg-config to find sqlite you may need to set:
      export PKG_CONFIG_PATH="/usr/local/opt/sqlite/lib/pkgconfig:$PKG_CONFIG_PATH"
      # Python 3.8
      # For compilers to find python@3.8 you may need to set:
      export LDFLAGS="-L/usr/local/opt/python@3.8/lib $LDFLAGS"
      # For pkg-config to find python@3.8 you may need to set:
      export PKG_CONFIG_PATH="/usr/local/opt/python@3.8/lib/pkgconfig:$PKG_CONFIG_PATH"
      # openssl
      # For compilers to find openssl@1.1 you may need to set:
      export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include $CPPFLAGS"
      export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib $LDFLAGS"
      # For pkg-config to find openssl@1.1 you may need to set:
      export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig:$PKG_CONFIG_PATH"
- name: Link configs
  tags: [config]
  file:
    src: "{{ playbook_dir }}/roles/ctags/files"
    dest: ~/.config/ctags
    state: link
