---
- name: Install from homebrew
  tags: [install]
  homebrew: name=zsh update_homebrew=yes
# https://wiki.archlinux.org/index.php/XDG_Base_Directory
# we are linking only zshenv into home dir
- name: Link zshenv
  tags: [config]
  file:
    src: "{{ playbook_dir }}/roles/zsh/files/zshenv"
    dest: ~/.zshenv
    state: link
- name: Link configs
  tags: [config]
  file:
    src: "{{ playbook_dir }}/roles/zsh/files"
    dest: ~/.config/zsh
    state: link
- name: Create local config
  tags: [config]
  file:
    dest: ~/.config/zsh/local.zsh
    state: touch
- name: Remove config from homedir
  tags: [config]
  file:
    path: ~/.zshrc
    state: absent
- name: Remove history file from homedir
  tags: [config]
  file:
    path: ~/.zsh_history
    state: absent
- name: Ensure cache dir
  tags: [config]
  file:
    path: ~/.cache/zsh
    state: directory
- name: Ensure cache dir for less
  tags: [config, less]
  file:
    path: ~/.cache/less
    state: directory
