---
- name: Install from homebrew
  tags: [install]
  homebrew: name=git update_homebrew=yes
- name: Link configs
  tags: [config]
  file:
    src: "{{ playbook_dir }}/roles/git/files"
    dest: ~/.config/git
    state: link
