---
- name: Install
  shell:
    cmd: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    creates: /usr/local/bin/brew
- name: Check analytics state
  shell: brew analytics state
  register: brew_analytics
- name: Disable analytics
  shell: brew analytics off
  when: brew_analytics.stdout != "Analytics are disabled."
- name: Update
  homebrew: update_homebrew=yes
