---
- name: Install
  shell:
    cmd: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    creates: /usr/local/bin/brew
- name: Check analytics state
  shell: brew analytics state
  register: brew_analytics
  check_mode: no
- name: Disable analytics
  shell: brew analytics off
  when: brew_analytics.stdout != "Analytics are disabled."
- name: Install apps
  tags: [install]
  homebrew:
    name:
      - mas
    update_homebrew: yes
- name: Install casks
  tags: [install, cask]
  homebrew_cask:
    name:
      - firefox
      - zoomus
      - notion
    update_homebrew: yes
- name: Install app store apps
  tags: [install, mas]
  shell:
    cmd: mas install {{ item }}
  loop:
    # copy'em paste
    - 876540291
    # telegram
    - 747648890
    # slack
    - 803453959
    # Pages
    - 409201541
    # Numbers
    - 409201541
    # Keynote
    - 409183694
