---
- name: Install
  shell:
    cmd: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    creates: /usr/local/bin/brew
- name: Check analytics state
  command: brew analytics state
  register: brew_analytics
  changed_when: brew_analytics.stdout != "Analytics are disabled."
  check_mode: no
- name: Disable analytics
  command: brew analytics off
  when: brew_analytics.stdout != "Analytics are disabled."
- name: Install apps
  tags: [install]
  homebrew:
    name:
      - mas
    update_homebrew: yes
- name: Install casks
  tags: [install, cask]
  homebrew_cask:
    name:
      - firefox
      # requires root
      # - zoomus
      - notion
    update_homebrew: yes
- name: List App Store apps
  tags: [mas, check]
  shell:
    cmd: mas list | cut -d ' ' -f 1
  register: mas_installed
  changed_when: false
  check_mode: no
- name: Install app store apps
  tags: [mas, install]
  command:
    cmd: mas install {{ item }}
  changed_when: "not mas_installed.stdout|regex_search(item | string, multiline=True)"
  loop:
    # copy'em paste
    - 876540291
    # telegram
    - 747648890
    # slack
    - 803453959
    # Pages
    - 409201541
    # Numbers
    - 409201541
    # Keynote
    - 409183694
