---
- name: homebrew | download Homebrew install script
  shell:
    cmd: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
    creates: /usr/local/bin/brew

- name: homebrew | chechk analytics state
  shell: brew analytics state
  register: brew_analytics

- name: homebrew | disable analytics
  shell: brew analytics off
  when: brew_analytics.stdout != "Analytics are disabled."

- name: homebrew | update Homebrew
  homebrew: update_homebrew=yes

