#!/bin/zsh

# https://github.com/git/git/blob/master/contrib/completion/git-prompt.sh
# https://unix.stackexchange.com/questions/53789/whats-the-newline-symbol-in-zshs-ps1
source $HOMEBREW_PREFIX/etc/bash_completion.d/git-prompt.sh

prompt_dotfiles_help () {
  cat <<'EOF'
This is dotfiles prompt

  prompt dotfiles
EOF
}

prompt_dotfiles_setup () {
  add-zsh-hook precmd prompt_dotfiles_precmd
}

prompt_dotfiles_precmd () {
  PROMPT="%F{blue}%~%f %F{yellow}$( __git_ps1 '[%s]' )%f${prompt_newline}%# "
}

prompt_dotfiles_setup "$@"
