---
- name: Install
  tags: [install]
  homebrew: name=tmux update_homebrew=yes
- name: Link configs
  tags: [config]
  file:
    src: "{{ playbook_dir }}/roles/tmux/files"
    dest: ~/.config/tmux
    state: link
