---
- name: Install direnv
  hosts: projecti
  remote_user: me
  tasks:
    - name: Install direnv
      become: yes
      apt: name=direnv update_cache=yes install_recommends=no
    - name: Add sourcing line
      blockinfile:
        path: ~/.config/bash/local.sh
        state: present
        marker: "# {mark} direnv ANSIBLE MANAGED BLOCK"
        block: |
          eval "$(direnv hook bash)"
          # https://github.com/direnv/direnv/wiki/Tmux
          alias tmux='direnv exec / tmux'
    - name: Link config
      tags: [configs, direnv]
      file:
        src: ~/development/dotfiles/minimal/direnv
        dest: ~/.config/direnv
        state: link
