---
- name: Setup dotfiles
  hosts: projecti
  remote_user: me
  tasks:
  - name: ensure private key is present
    copy:
      src: ~/.ssh/projecti_rsa
      dest: ~/.ssh/id_rsa
      mode: 0600
  - name: ensure public key is present
    copy:
      src: ~/.ssh/projecti_rsa.pub
      dest: ~/.ssh/id_rsa.pub
      mode: 0600
  - name: enable ssh-agent
    shell: 'eval "$(ssh-agent -s)" && ssh-add ~/.ssh/id_rsa'
  - name: Create a development directory if it does not exist
    file:
      path: ~/development
      state: directory
  - name: clone dotfiles repo
    git:
      repo: git@github.com:imomaliev/dotfiles.git
      dest: ~/development/dotfiles
      accept_hostkey: yes
  - name: Link nvim config
    tags: files
    file:
      src: ~/development/dotfiles/minimal/nvim
      dest: ~/.config/nvim
      state: link
  - name: Link tmux config
    tags: files
    file:
      src: ~/development/dotfiles/minimal/tmux/tmux.conf
      dest: ~/.tmux.conf
      state: link
  - name: Link bash config
    tags: files
    block:
    - name: Create symlink for bash
      file:
        src: ~/development/dotfiles/minimal/bash
        dest: ~/.config/bash
        state: link
    - name: Add sourcing line
      blockinfile:
        path: ~/.profile
        state: present
        marker: "# {mark} dotfiles ANSIBLE MANAGED BLOCK"
        block: |
          [[ -f "$HOME/.config/bash/bashrc" ]] && . $HOME/.config/bash/bashrc
    - name: Create local config file for bash
      file:
        dest: ~/.config/bash/local.sh
        state: touch
  - name: Link git config
    tags: files
    file:
      src: ~/development/dotfiles/minimal/git
      dest: ~/.config/git
      state: link
