---
- name: Setup dotfiles
  hosts: projecti
  remote_user: me
  tasks:
  - name: ensure private key is present
    copy:
      src: "~/.ssh/projecti_rsa"
      dest: "/home/me/.ssh/id_rsa"
      mode: 0600
  - name: ensure public key is present
    copy:
      src: "~/.ssh/projecti_rsa.pub"
      dest: "/home/me/.ssh/id_rsa.pub"
      mode: 0600
  - name: enable ssh-agent
    shell: 'eval "$(ssh-agent -s)" && ssh-add ~/.ssh/id_rsa'
  - name: Create a development directory if it does not exist
    file:
      path: ~/development
      state: directory
  - name: clone dotfiles repo
    git:
      repo: git@github.com:imomaliev/dotfiles.git
      dest: ~/development/dotfiles
      accept_hostkey: yes
  - name: Link nvim config
    block:
    - name: Create a nvim directory if it does not exist
      file:
        path: ~/.config/nvim
        state: directory
    - name: Create symlink for nvim
      file:
        src: ~/development/dotfiles/minimal/init.vim
        dest: ~/.config/nvim/init.vim
        state: link
  - name: Link tmux config
    file:
      src: ~/development/dotfiles/minimal/tmux.conf
      dest: ~/.tmux.conf
      state: link
  - name: Link bash config
    block:
    - name: Create a bash directory if it does not exist
      file:
        path: ~/.config/bash
        state: directory
    - name: Create symlink for bashrc
      file:
        src: ~/development/dotfiles/minimal/bashrc
        dest: ~/.config/bash/bashrc
        state: link
    - name: Add sourcing line
      blockinfile:
        path: ~/.profile
        state: present
        block: |
          # source dotfiles's bashrc
          [[ -f "$HOME/.config/bash/bashrc" ]] && . $HOME/.config/bash/bashrc
    - name: Create local config file for bash
      file:
        dest: ~/.config/bash/local.sh
        state: touch
