---
- name: Setup dotfiles
  hosts: projecti
  remote_user: me
  tasks:
  - name: ensure private key is present
    copy:
      src: ~/.ssh/projecti_rsa
      dest: ~/.ssh/id_rsa
      mode: 0600
  - name: ensure public key is present
    copy:
      src: ~/.ssh/projecti_rsa.pub
      dest: ~/.ssh/id_rsa.pub
      mode: 0600
  - name: enable ssh-agent
    shell: 'eval "$(ssh-agent -s)" && ssh-add ~/.ssh/id_rsa'
  - name: Create a development directory if it does not exist
    file:
      path: ~/development
      state: directory
  - name: clone dotfiles repo
    git:
      repo: git@github.com:imomaliev/dotfiles.git
      dest: ~/development/dotfiles
      accept_hostkey: yes
  - name: Link git config
    tags: [config, git]
    file:
      src: ~/development/dotfiles/minimal/git
      dest: ~/.config/git
      state: link
  - name: Link python config
    tags: [config, python]
    file:
      src: ~/development/dotfiles/minimal/python
      dest: ~/.config/python
      state: link
