---
- name: Install nvm
  hosts: projecti
  remote_user: me
  tasks:
  # https://github.com/nvm-sh/nvm#important-notes
  - name: Install nvm deps
    become: yes
    apt:
      name:
        - build-essential
        - libssl-dev
      update_cache: yes
      install_recommends: no
  - name: Download nvm-installer
    get_url:
      url: https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh
      dest: /tmp/nvm_installer
      mode: '0755'
  - name: Run installer
    command: "bash /tmp/nvm_installer"
  - name: Add bashrc config
    blockinfile:
      path: ~/.config/bash/local.sh
      state: present
      marker: "# {mark} nvm ANSIBLE MANAGED BLOCK"
      block: |
        export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
        [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
