---
- name: Install pipx
  hosts: projecti
  remote_user: me
  tasks:
    - name: Ensure python3-venv
      apt: name=python3-venv update_cache=yes install_recommends=no
      become: yes
    - name: Create opt folder
      file:
        path: ~/opt
        state: directory
    - name: Create default venv
      command: "python3 -m venv ~/opt/venv/"
    - name: Create install pipx
      command: "~/opt/venv/bin/pip install pipx"
    - name: Add venv PATH and PIPX path
      blockinfile:
        path: ~/.config/bash/local.sh
        state: present
        marker: "# {mark} pipx ANSIBLE MANAGED BLOCK"
        block: |
          export PATH="$HOME/.local/bin:$HOME/opt/venv/bin:$PATH"
