---
- name: Install Pyenv
  hosts: projecti
  remote_user: me
  tasks:
  # https://github.com/pyenv/pyenv/wiki/Common-build-problems#prerequisites
  - name: Install pyenv deps
    become: yes
    apt:
      name:
        - build-essential
        - libssl-dev
        - zlib1g-dev
        - libbz2-dev
        - libreadline-dev
        - libsqlite3-dev
        - llvm
        - libncurses5-dev
        - libncursesw5-dev
        - xz-utils
        - tk-dev
        - libffi-dev
        - liblzma-dev
        - python-openssl
      update_cache: yes
      install_recommends: no
  - name: Download pyenv-installer
    get_url:
      url: https://pyenv.run
      dest: /tmp/pyenv_installer
      mode: '0755'
  - name: Run installer
    command: "bash /tmp/pyenv_installer"
  - name: Add bashrc config
    blockinfile:
      path: ~/.config/bash/local.sh
      state: present
      marker: "# {mark} pyenv ANSIBLE MANAGED BLOCK"
      block: |
        export PATH="$HOME/.pyenv/bin:$PATH"
        eval "$(pyenv init -)"
        eval "$(pyenv virtualenv-init -)"
