---
- name: Install Pyenv
  hosts: projecti
  remote_user: me
  tasks:
    - name: Install pyenv deps
      apt:
        name: build-essential
      update_cache: yes
      install_recommends: no
      become: yes
    - name: Download pyenv-installer
      get_url:
        url: https://pyenv.run
        dest: /tmp/pyenv_installer
        mode: '0755'
    - name: Run installer
      shell: "bash /tmp/pyenv_installer"
    - name: Add bashrc config
      blockinfile:
        path: ~/.config/bash/local.sh
        state: present
        marker: "# {mark} pyenv ANSIBLE MANAGED BLOCK"
        block: |
          export PATH="$HOME/.pyenv/bin:$PATH"
          eval "$(pyenv init -)"
          eval "$(pyenv virtualenv-init -)"

