---
# https://github.com/andmarti1424/sc-im/wiki/Ubuntu-with-XLSX-import-&-export
- name: Setup sc-im
  hosts: projecti
  remote_user: me
  tasks:
  - name: Install sc-im deps
    become: yes
    apt:
      name:
        - bison
        - libncurses5-dev
        - libncursesw5-dev
        - libxml2-dev
        - libzip-dev
      update_cache: yes
      install_recommends: no
  - name: Create a tmp directory if it does not exist
    file:
      path: /tmp/sc-im
      state: directory
  - name: Install libxlsxwriter
    block:
    - name: clone repo
      git:
        repo: https://github.com/jmcnamara/libxlsxwriter.git
        dest: /tmp/sc-im/libxlsxwriter
    - name: Make
      make:
        chdir: /tmp/sc-im/libxlsxwriter
    - name: Run 'install' target as root
      make:
        chdir: /tmp/sc-im/libxlsxwriter
        target: install
      become: yes
    - name: Refresh the dynamic link library cache
      command: ldconfig
      become: yes
  - name: Install sc-im
    block:
    - name: clone repo
      git:
        repo: https://github.com/andmarti1424/sc-im.git
        dest: /tmp/sc-im/sc-im
    - name: Make
      make:
        chdir: /tmp/sc-im/sc-im/src
    - name: Run 'install' target as root
      make:
        chdir: /tmp/sc-im/sc-im/src
        target: install
      become: yes
