#!/usr/bin/env python3
# https://unix.stackexchange.com/a/121390

import os
import atexit
import readline


cache_dir = os.path.join(os.path.expanduser('~'), '.cache/python')
if not os.path.exists(cache_dir):
    os.makedirs(cache_dir)

readline_history_file = os.path.join(cache_dir, 'history')

try:
    readline.read_history_file(readline_history_file)
except IOError:
    pass

atexit.register(readline.write_history_file, readline_history_file)
