- name: Install
  tags: [install]
  homebrew_cask: name=alacritty update_homebrew=yes
- name: Link configs
  tags: [config]
  file:
    src: "{{ playbook_dir }}/roles/alacritty/files"
    dest: ~/.config/alacritty
    state: link
  # https://github.com/alacritty/alacritty/blob/master/INSTALL.md#terminfo
  # https://github.com/Homebrew/homebrew-cask/pull/118146/files
# - name: Setup terminfo
#   tags: [setup]
#   block:
#     - name: Check that the terminfo exists
#       tags: [setup]
#       stat:
#         path: $HOME/.terminfo/61
#       register: terminfo_stat
#     - name: Check that the terminfo exists
#       blockinfile:
#         path: ~/.config/zsh/local.zsh
#         state: absent
#         marker: "# {mark} alacritty ANSIBLE MANAGED BLOCK"
#         block: |
#           export TERMINFO_DIRS="$TERMINFO:$HOME/.terminfo"
# - name: ~
#   file:
#     src: "$HOME/.terminfo/61"
#     dest: ~/.config/alacritty
#     state: link
#   when: terminfo_stat.stat.exists
