alias ls='ls --color -la'
alias watch='watch --color'
alias grep='grep --color'
alias vim='nvim'
alias cal='gcal'
alias noveo_connect='sshfs noveo:$HOME/Development ~/Noveo/Remote/'
alias noveo_disconnect='umount ~/Noveo/Remote/'
alias docker_rm='docker rm $(docker ps -a -q)'
alias docker_rmi='docker rmi $(docker images -q -f dangling=true)'
